### ISSUE TITLE
V1.2.2 can't find GAMS

### ISSUE THREAD

**Issue by acjbrouwer** [chrispahm/linter-gams#14]
I have GAMS on-path, but on atom startup, a dialog appears stating _No GAMS Installation Found_. Configuring the GAMS path is not possible because the settings show the _Scratch directory_ configuration but not the _Gams Executable_ configuration [shown here](https://github.com/chrispahm/linter-gams#configuration).

**Comment by chrispahm** [comment]
Thanks for raising the issue! This problem occurres on some machines (on which I unfortunately don’t have access to) and I’m still trying to figure out why it happens. Could you give me some more info on your setup? I have a feeling this happens on x86 machines where neither the path is found nor glob finds the gams installation

**Comment by acjbrouwer** [comment]
It is an x86 machine indeed. Windows 10 64bit. Both C:\GAMS\win64\25.1 and C:\GAMS\win64\25.1\gbin are part of the PATH environment variable,

**Comment by acjbrouwer** [comment]
Thank you, the patch works.

On inspecting `getGamsPath()`, I noticed that it neither returns `gamsExec` as queried by `shell.which()` nor replaces `\` path separators with `/`. The following fixed `getGamsPath()` works for me without the patch having been applied.

```javascript
getGamsPath() {
  let gamsExec = shell.which('gams')
  if(gamsExec) {
    if (os.platform() === 'win32') {
      gamsExec = gamsExec.replace(/\\/g, '/')
    }
    return gamsExec
  }
  // if not found, check in standard directories
  else {
    // in case of windows
    if (os.platform() === 'win32') {
      if (glob.sync('C:\\GAMS\\*\\*\\').length > 0) {
        gamsExec = glob.sync('C:/GAMS/*/*/')[glob.sync('C:/GAMS/*/*/').length - 1] + 'gams.exe'
        window.alert('Here')
        window.alert(gamsExec)
        return gamsExec
      } 
      else if (glob.sync('N:\\soft\\GAMS*\\').length > 0) {
        gamsExec = glob.sync('N:\\soft\\GAMS*\\')[glob.sync('N:\\soft\\GAMS*\\').length - 1] + 'gams.exe'
        return gamsExec
      } else {
        this.alert('noGAMS')
        return ''
      }
    }
    // and mac
    else if (os.platform() === 'darwin') {
      if (glob.sync('/Applications/GAMS*/sysdir/').length > 0) {
        gamsExec = glob.sync('/Applications/GAMS*/sysdir/')[glob.sync('/Applications/GAMS*/sysdir/').length - 1] + 'gams'
        return gamsExec
      } else {
        this.alert('noGAMS')
        return ''
      }
    } else {
      this.alert('noGAMS')
      return ''
    }
  }
},
```

**Comment by chrispahm** [comment]
Thanks a lot for your help! You were perfectly right, I never really tested that part through. Also, after carefully reading through the [Node glob docs](https://www.npmjs.com/package/glob#windows) I found out only forward-slashes are allowed on Windows glob-expressions.
Sorry for that, I just published the patch and hope the issue should be gone by now.
Would be nice if you could confirm!

**Comment by acjbrouwer** [comment]
Confirmed: after upgrading to V1.2.3, linter-gams works (no complaint on startup, errors in GAMS code are detected). For good measure, I took GAMS off-path, restarted atom, and then too it works.

Thanks!

**Comment by chrispahm** [comment]
Perfect, closing this issue then!

**Comment by chrispahm** [comment]
By the way, this morning I got [noticed](https://discuss.atom.io/t/filter-lines-containing-string-and-be-able-to-edit/53376/4) about a really helpful package for GAMS development / LST file investigation: It's called [filter-lines](https://github.com/jessexknight/atom-filter-lines)

**Comment by samarthiith** [comment]
Hi, 
thanks for this package. Looks really good. 
I have installed the latest version. however, the error persists. 
I was able to remove the error by manually specifying the path in the linter-gams, linter.js file. However, it still shows error in the in the gams-helper package. 

Where should I change the code in the gams-helper.js file?

Very much appreciate the help. 
thanks!
